allowBuilds:
  '@firebase/util': true
  '@parcel/watcher': true
  cypress: true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  protobufjs: true
minimumReleaseAge: 10080 # 7 days
minimumReleaseAgeExclude:
  # Renovate security update: @angular/core@22.0.1
  - "@angular/core@22.0.1"
