export const e = {
  logo: '[data-test-id="logo"]',
  topbarMenu: '[data-test-id="topbar-menu"]',
  showItem: '[data-test-id="show"]',
  showItemMenu: '[data-test-id="show-item-menu"]',
  showItemAddButton: '[data-test-id="add-button"]',
  showItemRemoveButton: '[data-test-id="remove-button"]',
  showItemAdded: '[data-test-id="show-added"]',
  searchInput: '[data-test-id="search"]',
  addShowSearchInput: '[data-test-id="add-show-search"]',
  showPosterImage: '[data-test-id="poster-image"]',
  episodePreviousButton: '[data-test-id="previous-button"]',
  episodeNextButton: '[data-test-id="next-button"]',
  listAddButton: '[data-test-id="add-list-button"]',
  listRemoveButton: '[data-test-id="remove-list-button"]',
  listAddInput: '[data-test-id="add-list"]',
};
