name: E2E tests

on: [ push ]

jobs:
  cypress-run:
    if: ${{ false }}  # disable for now
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Setup pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6
        with:
          cache: true

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@948d67d3074f1bbb6379c8bdbb04e95d2f8e593f # v7.4.0
        with:
          start: pnpm start
          # quote the url to be safe against YML parsing surprises
          wait-on: 'http://localhost:4200'
        env:
          CYPRESS_EMAIL: ${{ secrets.CYPRESS_EMAIL }}
          CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}
          CYPRESS_ACCESSTOKEN: ${{ secrets.CYPRESS_ACCESSTOKEN }}
          CYPRESS_REFRESHTOKEN: ${{ secrets.CYPRESS_REFRESHTOKEN }}
          CYPRESS_EXPIRESAT: ${{ secrets.CYPRESS_EXPIRESAT }}
          CYPRESS_ACCESSTOKENSTOREDAT: ${{ secrets.CYPRESS_ACCESSTOKENSTOREDAT }}

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        if: failure()
        with:
          name: cypress-data
          path: |
            cypress/videos
            cypress/screenshots
