name: E2E tests

on: [ push ]

jobs:
  cypress-run:
    if: ${{ false }}  # disable for now
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup pnpm
        uses: pnpm/action-setup@91ab88e2619ed1f46221f0ba42d1492c02baf788 # v6
        with:
          cache: true

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@c495c3ddffba403ba11be95fffb67e25203b3799 # v7.1.10
        with:
          start: pnpm start
          # quote the url to be safe against YML parsing surprises
          wait-on: 'http://localhost:4200'
        env:
          CYPRESS_EMAIL: ${{ secrets.CYPRESS_EMAIL }}
          CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}
          CYPRESS_ACCESSTOKEN: ${{ secrets.CYPRESS_ACCESSTOKEN }}
          CYPRESS_REFRESHTOKEN: ${{ secrets.CYPRESS_REFRESHTOKEN }}
          CYPRESS_EXPIRESAT: ${{ secrets.CYPRESS_EXPIRESAT }}
          CYPRESS_ACCESSTOKENSTOREDAT: ${{ secrets.CYPRESS_ACCESSTOKENSTOREDAT }}

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        if: failure()
        with:
          name: cypress-data
          path: |
            cypress/videos
            cypress/screenshots
